// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by UnitySpec (https://github.com/mmulder135/UnitySpec).
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Samples.SimpleMovement.SampleMovementTests
{
    using UnitySpec;
    using System;
    using System.Linq;

    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("WASD moves player")]
    public partial class WASDMovesPlayerFeature
    {
        private static string[] featureTags = ((string[])(null));
        [UnityEngine.TestTools.UnityTestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Basic movement: w")]
        public System.Collections.IEnumerator BasicMovement_W()
        {
            {
#line 5
                return this.BasicMovement("w", "forward", ((string[])(null)));
            }
        }

        [UnityEngine.TestTools.UnityTestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Basic movement: a")]
        public System.Collections.IEnumerator BasicMovement_A()
        {
            {
#line 5
                return this.BasicMovement("a", "left", ((string[])(null)));
            }
        }

        [UnityEngine.TestTools.UnityTestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Basic movement: s")]
        public System.Collections.IEnumerator BasicMovement_S()
        {
            {
#line 5
                return this.BasicMovement("s", "backward", ((string[])(null)));
            }
        }

        [UnityEngine.TestTools.UnityTestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Basic movement: d")]
        public System.Collections.IEnumerator BasicMovement_D()
        {
            {
#line 5
                return this.BasicMovement("d", "right", ((string[])(null)));
            }
        }

        public System.Collections.IEnumerator BasicMovement(string key, string direction, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("key", key);
            argumentsOfScenario.Add("direction", direction);
            UnitySpec.ScenarioInfo scenarioInfo = new UnitySpec.ScenarioInfo("Basic movement", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 5
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
                yield return ((System.Collections.IEnumerator)(testRunner.Given("I load the level \"MoveTest\"", (string)(null), (UnitySpec.Table)null, "Given ")));
#line 7
                yield return ((System.Collections.IEnumerator)(testRunner.And("I have a position", (string)(null), (UnitySpec.Table)null, "And ")));
#line 8
                yield return ((System.Collections.IEnumerator)(testRunner.When(String.Format("I press {0} for 1 second", key), (string)(null), (UnitySpec.Table)null, "When ")));
#line 9
                yield return ((System.Collections.IEnumerator)(testRunner.Then(String.Format("I have moved {0}", direction), (string)(null), (UnitySpec.Table)null, "Then ")));
            }

            this.ScenarioCleanup();
        }

        private UnitySpec.ITestRunner testRunner;
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public void FeatureSetup()
        {
            testRunner = UnitySpec.TestRunnerManager.GetTestRunner(null, 0);
            UnitySpec.FeatureInfo featureInfo = new UnitySpec.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "C:/Users/Michael/Documents/Unity Learn/UnityFlow dotNet Standard/Assets/Specs/Tests/Features", "WASD moves player", "    As a user\r\n    I want to be able to move using wasd-keys", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }

        public void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }

        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public void ScenarioInitialize(UnitySpec.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }

        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }

        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
    }
}
#pragma warning restore
#endregion
